# Используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk18

# После выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo.
# Здесь используется сторонни сервис https://codecov.io/.
after_success:
  - bash <(curl -s https://codecov.io/bash)

  # Определяем операционную систему.
  os: windows

# Отправлять уведомление на почту IuriyG@protonmail.com.
notifications:
  email:
    recipients:
      -IuriyG@protonmail.com
    on_success: never # default: change
    on_failure: always # on_error: always
